# Set the base image to Python
FROM python:3.10-slim-buster

# Copy the Python script and requirements to the image
COPY producer.py requirements.txt /services/
RUN pip install -r /services/requirements.txt

# Set the working directory to /services
WORKDIR /services

# Run the Python script when the container starts
CMD ["python", "producer.py"]
