{
 "title": "Kafka stores",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "Shop", "query": "SELECT name FROM public.shops" }
  ]
 },
 "panels": [
  {
   "title": "Information about the selected shop",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select\n  name as \"Shop Name\",\n  id as \"Shop ID\",\n  latitude as \"Latitude\",\n  longitude as \"Longitude\",\n  (shops.name = '$Shop') as selected\nfrom public.shops;"
    }
   ]
  },
  {
   "title": "Log of orders",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "with cte as (\n\tselect\n\t\torders.order_date,\n\t\torders.id,\n\t\torders.shop_id,\n\t\torders.product_id,\n\t\tshops.name\n\tfrom\n\t\torders\n\tleft join\n\t\tshops on\n\t\t\torders.shop_id = shops.id\n\twhere\n\t\torders.order_date between now() - interval '130 MINUTES' and now()\n\t\tand shops.name = '$Shop'\n)\nselect\n\tcte.order_date as \"Order date\",\n\tcte.shop_id as \"Shop ID\",\n\tcte.name as \"Shop name/address\",\n  STRING_AGG(products.\"name\", ', ') as \"Products sold\",\n  count(distinct cte.product_id) as \"Number of products sold\",\n  sum(price) as \"Total\"\nfrom\n\tcte\nleft join\n\tproducts on\n\t\tcte.product_id = products.id\ngroup by\n\tcte.shop_id,\n\tcte.id,\n\tcte.name,\n\tcte.order_date\norder by cte.order_date desc\nlimit 30;"
    }
   ]
  },
  {
   "title": "Total number of products sold",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "with cte as (\n\tselect\n\t\torders.shop_id,\n\t\torders.product_id,\n\t\tcount(orders.product_id) as count_product\n\tfrom\n\t\torders\n\tgroup by\n\t\torders.shop_id,\n\t\torders.product_id\n)\nselect\n\tcte.shop_id as \"Shop ID\",\n\tshops.name as \"Shop name/address\",\n\tcte.product_id \"Product ID\",\n\tproducts.name as \"Product name\",\n\tcount_product as \"Total number sold\"\nfrom\n  cte\nleft join\n\tshops on\n\t\tcte.shop_id = shops.id\nleft join\n\tproducts on\n\t\tcte.product_id = products.id\nwhere shops.name = '$Shop'\norder by \"Total number sold\" desc;"
    }
   ]
  },
  { "title": "Information about all shops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total count of orders per shop",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH CTE AS (\nSELECT\n  shop_id,\n  count(id) as \"count_orders\"\nFROM\n  orders\nWHERE \"orders\".\"order_date\" BETWEEN NOW() - INTERVAL '1 HOURS' AND NOW()\nGROUP BY \"shop_id\"\n)\nSELECT\n  CAST(shop_id AS TEXT) as \"Shop ID\",\n  count_orders as \"Total count of orders\",\n  name as \"Shop name/address\"\nFROM\n  cte\nLEFT JOIN\n  shops ON\n    cte.shop_id = shops.id"
    }
   ]
  },
  {
   "title": "Mean revenue per order for each shop",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "with cte as (\n\tselect\n\t\torders.shop_id,\n\t\torders.id,\n\t\tsum(products.price) as total_amount\n\tfrom\n\t\torders\n\tleft join\n\t\tproducts on\n\t\t\torders.product_id = products.id\n\tgroup by\n\t\torders.shop_id,\n\t\torders.id\n),\ncte_mean as (\n  select\n  \tcte.shop_id,\n  \tavg(total_amount)\n  from\n  \tcte\n  left join\n  \tshops on\n  \t\tcte.shop_id = shops.id\n  group by\n  \tcte.shop_id\n)\nselect\n\tshops.name as \"Shop name/address\",\n\tCAST(cte_mean.shop_id AS TEXT) as \"Shop ID\",\n\tcte_mean.avg as \"Mean revenue per order for each shop\"\nfrom\n  cte_mean\nleft join\n\tshops on\n\t\tcte_mean.shop_id = shops.id;"
    }
   ]
  },
  {
   "title": "Revenue and costs per shop",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "WITH CTE AS (\n  SELECT\n    orders.shop_id,\n    sum(products.price) as \"sum_price\",\n    sum(products.cost) as \"sum_cost\"\n  FROM\n    orders\n  LEFT JOIN\n    products ON\n      orders.product_id = products.id\n  WHERE \"orders\".\"order_date\" BETWEEN NOW() - INTERVAL '3 HOURS' AND NOW()\n  GROUP BY \"shop_id\"\n)\nSELECT\n  CAST(shop_id AS TEXT) as \"Shop ID\",\n  sum_price as \"Total revenue\",\n  sum_cost as \"Total costs\",\n  name as \"Shop name/address\"\nFROM\n  cte\nLEFT JOIN\n  shops ON\n    cte.shop_id = shops.id\nORDER BY \"Total revenue\" DESC;"
    }
   ]
  }
 ]
}